//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _15_Puzzle_Game.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaderBoards
    {
        public int user_id { get; set; }
        public int puzzle_id { get; set; }
        public int level_id { get; set; }
        public int move { get; set; }
        public int time_taken { get; set; }
    
        public virtual Levels Levels { get; set; }
        public virtual Puzzles Puzzles { get; set; }
        public virtual Users Users { get; set; }
    }
}
