//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _15_Puzzle_Game.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserImages
    {
        public int image_id { get; set; }
        public int user_id { get; set; }
        public byte[] image_byte { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
